### ISSUE TITLE
Add check-only version of the middleware

### ISSUE THREAD

**Issue by kronthto** [kronthto/laravel-oauth2-login#1]
The current `CheckOAuth2` checks the auth, and redirect the User to the OAuth-Authorize-URL if invalid/not logged in.

It is currently not possible to just "check", inject the attributes if logged in, or `null/false` if not. A usecase would be to display a Login/Logout button, but not force-login the user.

* Add an alternative middleware that instead of returning a redirect just calls `$next` without setting "loggedIn"
* Do this via config / middleware-param switch?
* It should work with `Auth::check`

**Comment by obahareth** [comment]
I've actually found myself in need of this and I think an alternative middleware would be a good start.

**Comment by kronthto** [comment]
Will be in the next release (1.8.0). The new middleware will just check and inject the Request attributes if the user is logged. 
So you will need to check for the existence of those attribute / or use the Custom Guard.
