### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by iainheng** [kronthto/laravel-oauth2-login#11]
Hi, great package and it saves me a lot of time. 👍🏼

May I know is there any elegant way to logout user?

**Comment by kronthto** [comment]
`Auth::logout()` would only be possible when implementing `StatefulGuard`, which this package doesn't do by design currently.
Either the middleware only injects the user info or a `RequestGuard` is used.

I use this package myself in application where I need logout, the way I do it is not elegant:
```php
session()->remove('oauth2_auth_state');
session()->remove('oauth2_session');
```

**Comment by iainheng** [comment]
Thanks for the heads up. 👍🏻 I am doing the same now by invalidating the session.
