### ISSUE TITLE
Authenticate from JS

### ISSUE THREAD

**Issue by iainheng** [kronthto/laravel-oauth2-login#12]
Do we need to pass `access token` manually in headers when we are accessing protected routes from javascript/AJAX? 

Example with axios:
```
axios.defaults.headers.common = {
    'Authorization': 'Bearer ' + Laravel.apiToken,
};
```

Is this the correct way to do this?

**Comment by kronthto** [comment]
I don't fully understand your usecase, this package is meant to authorize users on Web routes, not for API authentication.

If you want to access protected internal (Same-Site) api-routes with AJAX that is fine, but you shouldn't need to pass any token. Make it a normal web route that uses the session, the AJAX-request should include the session cookie already and be authenticated.

**Comment by iainheng** [comment]
I'm sorry. I made a mistake and forgot to include `\Kronthto\LaravelOAuth2Login\CheckOAuth2` middleware in the protected routes. 

I fixed it and it is working fine now. Sorry for my dumb question earlier. 😓
