### ISSUE TITLE
How to fetch logged in user?

### ISSUE THREAD

**Issue by obahareth** [kronthto/laravel-oauth2-login#4]
Hey @kronthto,

Thanks for making this awesome package!

I wanted to ask how do I get the currently logged in user. I followed the README instructions and do have the OAuth flow working and everything is being stored in the session as expected, but it's not clear to me how to get the currently logged in user.

`Auth::user()` returns `null`, how am I supposed to get the user?

**Comment by obahareth** [comment]
I seem to have gotten it working by putting the `oauth2` driver on my `web` guard by doing this:


```php
// config/auth.php
'guards' => [
    'web' => [
        'driver' => 'oauth2',
    ],
],
```

My Laravel is a bit rusty, does that seem like the right way to do it? Because I see in the README it says to do it like so:

```php
'oauth2' => [
  'driver' => 'oauth2', // Config: oauth2login.auth_driver_key
]
```

**Comment by kronthto** [comment]
Hi,

As you have noticed, by default you won't get the User via `Auth / auth()`. You can always access the "Resource-Owner" object returned by your OAuth-Server (IP) from the Request attributes though, it is injected there: `$request->attributes->get(config('oauth2login.resource_owner_attribute'))`

Or, as you have read in the Readme, setup the guard, so you can utilize `Auth`. What you did works, but you assigned the `oauth2` **driver** directly to the web **guard**. That's not necessarily bad. 
I however prefered to define a custom **guard** `oauth2` using that **driver**, and then use that **guard** when needed (`Auth::guard('oauth2')->user()`) or make it the default guard. My config: 
```php
    'defaults' => [
        'guard' => 'oauth2',
        // ...
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        // ...
        'oauth2' => [
            'driver' => 'oauth2',
        ],
    ],
```

Happy holidays!

**Comment by obahareth** [comment]
Thanks a lot once again @kronthto for your help and this package (it's been a major time saver)!

Sorry for the dumb question, it's been 4 years since I last used Laravel and I now have to maintain a Laravel project and I'm quite rusty.
