### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by elliotlings** [kronthto/laravel-oauth2-login#7]
Does this work with Laravel 5.8?

**Comment by kronthto** [comment]
The `composer.json` restraints it to 5.7 currently / does not allow 5.8.

I'll test it with 5.8 probably on the weekend / review the changes.

In the past upgrading didn't make any big problems.

**Comment by kronthto** [comment]
Except for [2 smaller adjustments](https://github.com/kronthto/laravel-oauth2-login/compare/v1.6.0...v1.7.0) I couldn't find any issues & it worked in my test 5.8 project.

So I released [v1.7.0](https://github.com/kronthto/laravel-oauth2-login/releases/tag/v1.7.0) that should now work with L5.8.

Closing this issue therefore, if there are issues just ping me 😉.

**Comment by elliotlings** [comment]
Great, thank you!
