### ISSUE TITLE
Exception when refresh token is expired

### ISSUE THREAD

**Issue by tumarov** [kronthto/laravel-oauth2-login#8]
I suggest to insert this line
https://github.com/kronthto/laravel-oauth2-login/blob/1fe7f9748eab1ae97befaff68831ae00d052e076/src/CheckOAuth2.php#L34
before line
https://github.com/kronthto/laravel-oauth2-login/blob/1fe7f9748eab1ae97befaff68831ae00d052e076/src/CheckOAuth2.php#L37
inside try block to catch exceptions during refreshing token.
I have one inconvenient issue: when refresh token is expired, I get [IdentityProviderException](oauth2-client/src/Provider/Exception/IdentityProviderException.php) with message "invalid_grant. refresh token is expired". This is my first time of oauth using, but it seems to me it would be better to redirect user to auth endpoint to begin auth process from the beginning instead of throw exception). 
Now to solve this problem I have to create my own middleware extending [CheckOAuth2](laravel-oauth2-login/src/CheckOAuth2.php) where handle method has described logic above.

**Comment by kronthto** [comment]
Sorry for late response..

The refresh-token shouldn't expire all that often though, at least in the contexts I worked with it never had an expiration time and if anything was manually revoked.

You are correct though that error-handling should be added. I will look into this / where to add it best, your suggestion seems viable too.

**Comment by kronthto** [comment]
I implemented your suggested change in [v1.7.1](https://github.com/kronthto/laravel-oauth2-login/releases/tag/v1.7.1), does that solve your issue?

**Comment by tumarov** [comment]
Yes, that does. Thank you.
