### ISSUE TITLE
Check globally if the user is connected

### ISSUE THREAD

**Issue by StevenAvelino24** [kronthto/laravel-oauth2-login#9]
Hello,

The package works well, however, if I want to check if the user is connected on a route that doesn't use the middleware, how would I do it ?
I've seen that to check if the user is connected, you pass the owner resources as an attribute to the request, could it be possible to check for the session all the time instead ?

**Comment by kronthto** [comment]
I noticed that this is a valid usecase too, see #1.

Currently it's only possible by manually checking the session, yes.

I will try to look into it again.

**Comment by kronthto** [comment]
Newest release ([1.8.0](https://github.com/kronthto/laravel-oauth2-login/releases/tag/v1.8.0)) contains this "CheckOnly" middleware. Use this on the routes you want to check the session only (and inject Request attributes if OK) but not redirect. Hope this solves your use case.
